sudo: required

language: minimal

services:
- docker

os:
- linux
- windows

env:
- CHANNEL=stable
- CHANNEL=beta
- CHANNEL=nightly

matrix:
  fast_finish: true
  allow_failures:
  - env: CHANNEL=nightly


script:
- docker build -t magnonellie/amethyst-docker-cache:$CHANNEL --build-arg CHANNEL=$CHANNEL .

deploy:
  provider: script
  script: bash push.sh
