sudo: required

language: minimal

services:
- docker

os:
- linux

env:
- CHANNEL=stable
- CHANNEL=beta
- CHANNEL=nightly

script:
- docker build -t magnonellie/amethyst-dependencies:$CHANNEL --build-arg CHANNEL=$CHANNEL $TRAVIS_OS_NAME
- |
  if [ ${CHANNEL} == "stable" ]
  then
    docker tag magnonellie/amethyst-dependencies:$CHANNEL magnonellie/amethyst-dependencies:latest
  fi


deploy:
  provider: script
  script: bash push.sh
